name: Low Stock Scheduler

on:
  schedule:
    - cron: "* * * * *" # setiap 1 menit
  workflow_dispatch: # ⬅️ ini penting

jobs:
  hit-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X GET "https://warungkuu-api.vercel.app/jobs/low-stock"
